#MIN
diabetest1&lt;-read_excel(&quot;C:/Users/M.Geetha/Downloads/NARA.xlsx&quot;)
A&lt;-c(diabetest1$Age)

Minimum&lt;-Min(diabetest1$Age)
#MAX
diabetest1&lt;-read_excel(&quot;C:/Users/M.Geetha/Downloads/NARA.xlsx&quot;)
A&lt;-c(diabetest1$Age)
Maximum&lt;-Max(diabetest1$Age)
#MEAN
diabetest1&lt;-read_excel(&quot;C:/Users/M.Geetha/Downloads/NARA.xlsx&quot;)
A&lt;-c(diabetest1$Age)
Mean&lt;-mean(A)
#MINMAX
diabetest1&lt;-read_excel(&quot;C:/Users/M.Geetha/Downloads/NARA.xlsx&quot;)
A&lt;-c(diabetest1$Age)
Maximum&lt;-Max(diabetest1$Age)
Minimum&lt;-Min(diabetest1$Age)
MinMax&lt;-(A-Minimum)/(Maximum-Minimum)
MinMax
